### ISSUE TITLE
webP using "sharp" : 'textureCompress' not found in "@gltf-transform/functions"

### ISSUE THREAD

**Issue by optimus007** [nytimes/rd-bundler-3d-plugins#12]
I'm trying to replicate gltfjsx library's default output which uses webP for images using sharp as encoder
(reason :  My 17mb glb file becomes 1.5mb in gltfjsx and 8mb via vite-plugin-gltf and i'm guessing it's due to webP images)

vite config Code:
```
import gltf from "vite-plugin-gltf" // Vite
import {
   ...
  textureCompress,
} from "@gltf-transform/functions"
import sharp from "sharp"

transforms: [
       ...
        textureCompress({
          targetFormat: "webp",
          encoder: sharp,
          resize: [resolution, resolution],
        }),
      ...
      ],

```

but 'textureCompress' is not included in "@gltf-transform/functions" 
how do i proceed here ? is this the best way ?

webP code referred from [here](https://github.com/pmndrs/gltfjsx/blob/master/src/utils/transform.js)

_The way this compresses glb on build is superb !_

**Comment by juniorxsound** [comment]
Thanks @optimus007! which version of `@gltf-transform/functions` are you using? looks like `gltfjsx` is using `^3.0.0-alpha.3` (see [this](https://github.com/pmndrs/gltfjsx/blob/master/package.json#L39-L41))

**Comment by juniorxsound** [comment]
I guess to support this we might also want to update our peerDependency on `@2.x` ([here](https://github.com/nytimes/rd-bundler-3d-plugins/blob/main/packages/core/package.json#L21-L23))- @donmccurdy what do you think?

**Comment by optimus007** [comment]
yeah, i only installed vite-plugin-gltf which auto installed 2.5.1 of gltf/transform

**Comment by donmccurdy** [comment]
gltfjsx is using the glTF Transform v3 prerelease —

```
npm install --save @gltf-transform/core@next @gltf-transform/extensions@next @gltf-transform/functions@next
```

I can't promise the v3 prerelease won't have more breaking changes before it becomes stable, but the only _planned_ breaking change left now is a switch to ES Modules (see: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), which shouldn't matter in this context. Or v3 may have some bugs I haven't caught yet.

I think it'd be safe to loosen the peer dependencies here, allowing users to choose either v2 or v3. All code in the vite and rollup plugins should be compatible with both versions, only the [example usage](https://github.com/nytimes/rd-bundler-3d-plugins#examples) would need updates for v3.

**Comment by optimus007** [comment]
that worked !

17mb gltf to 1.5mb 

config
```
plugins: [
    gltf({
      transforms: [
        // remove unused resources
        prune(),

        // combine duplicated resources
        dedup(),

        textureCompress({
          targetFormat: "webp",
          encoder: sharp,
          resize: [resolution, resolution],
        }),

        // compress mesh geometry
        draco(),
      ],
    }),
  ],
```
