### ISSUE TITLE
Add to Vite and Rollup plugin registries

### ISSUE THREAD

**Issue by donmccurdy** [nytimes/rd-bundler-3d-plugins#15]
In progress:

- [ ] https://github.com/rollup/awesome/pull/112
- [x] https://github.com/vitejs/awesome-vite/pull/660

**Comment by juniorxsound** [comment]
@donmccurdy Looks like this is complete right?

**Comment by donmccurdy** [comment]
Complete enough for now I think! If we get around to adding unit tests I guess we could try again on the Rollup PR.
